#------------------------------------------------------------
# Values for this lesson.
#------------------------------------------------------------

# Which carpentry is this (swc, dc, lc, or cp)?
# swc: Software Carpentry
# dc: Data Carpentry
# lc: Library Carpentry
# cp: Carpentries (to use for instructor training for instance)
# incubator: The Carpentries Incubator
# Note that you can also use a custom carpentry type. For more info,
# see the documentation: https://carpentries.github.io/sandpaper-docs/editing.html
carpentry: 'uom'

# Custom carpentry description
# This will be used as the alt text for the logo
# carpentry_description: "Custom Carpentry"

# Overall title for pages.
title: 'Intro to Metabarcoding using QIIME2 - Mammal Dataset'

# Date the lesson was created (YYYY-MM-DD, this is empty by default)
created: 

# Comma-separated list of keywords for the lesson
keywords: 'metabarcoding, QIIME2, microbiome '

# Life cycle stage of the lesson
# possible values: pre-alpha, alpha, beta, stable
life_cycle: 'pre-alpha'

# License of the lesson materials (recommended CC-BY 4.0)
license: 'CC-BY 4.0'

# Link to the source repository for this lesson
source: 'https://github.com/rpapaluca/intro-QIIME2-mammal'

# Default branch of your lesson
branch: 'main'

# Who to contact if there are any issues
contact: 'fixme@fixme.org'

# Navigation ------------------------------------------------
#
# Use the following menu items to specify the order of
# individual pages in each dropdown section. Leave blank to
# include all pages in the folder.
#
# Example -------------
#
# episodes:
# - introduction.md
# - first-steps.md
#
# learners:
# - setup.md
#
# instructors:
# - instructor-notes.md
#
# profiles:
# - one-learner.md
# - another-learner.md

# Order of episodes in your lesson
episodes: 
- introduction.md
- background.Rmd
- section-1-importing-cleaning-and-quality-control-of-the-data.Rmd
- section-2-taxonomic-analysis.Rmd
- section-3-build-a-phylogenetic-tree.Rmd
- section-4-basic-visualisations-and-statistics.Rmd
- section-5-exporting-data-for-further-analysis-in-r.Rmd

# Information for Learners
learners: 

# Information for Instructors
instructors: 

# Learner Profiles
profiles: 

# Customisation ---------------------------------------------
#
# This space below is where custom yaml items (e.g. pinning
# sandpaper and varnish versions) should live


carpentry_description: Lesson Description
varnish: melbournebioinformatics/uom-varnish@main
url: melbournebioinformatics.github.io/uom-varnish
