---
title: 'Initial Set Up with Nectar'
teaching: 10
exercises: 0
---

:::::::::::::::::::::::::::::::::::::: questions 

- Why is it important to use a byobu-screen session when working on a remote instance like Nectar?
- What is the purpose of creating symbolic links (ln -s) to shared data rather than copying files directly?

::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives

- Initiate and reconnect to a persistent terminal session using byobu-screen to ensure long-running commands continue even after disconnection.
- Create symbolic links to shared workshop files in order to efficiently access large datasets without duplicating them. 

::::::::::::::::::::::::::::::::::::::::::::::::

## Byobu-screen
To ensure that commands continue to run should you get disconnected from your Nectar Instance, we’ll run a [byobu-screen](https://www.melbournebioinformatics.org.au/tutorials/tutorials/workshop_delivery_mode_info/workshops_nectar/#byobu-screen) session.

#Starting a byobu-screen session
On Nectar, to start a byobu-screen session called workshop, type

``` bash
byobu-screen -S workshop
```

#Reconnecting to a byobu-screen session
If you get disconnected from your Nectar Instance, [follow the instructions here](https://www.melbournebioinformatics.org.au/tutorials/tutorials/workshop_delivery_mode_info/workshops_nectar/#reconnecting-to-a-byobu-screen-session) to resume your session.

## Symbolic links to workshop data
Data for this workshop is stored in a central location (/mnt/shared_data/) on the Nectar file system that we will be using. We will use symbolic links (ln -s) to point to it. 

Symbolic links (or symlinks) are just “virtual” files or folders (they only take up a very little space) that point to a physical file or folder located elsewhere in the file system. 

Sequencing data can be large, and rather than unnecessarily having multiple copies of the data which can quickly take up a lot of space, we will simply point to the files needed in the shared_data folder.

``` bash
cd
ln -s /mnt/shared_data/raw_data raw_data
ln -s /mnt/shared_data/echidna_metadata.tsv echidna_metadata.tsv
ln -s /mnt/shared_data/silva_138_16s_515-806_classifier.qza silva_138_16s_515-806_classifier.qza
```

